working domestic payment
cloudentity/openbanking-sample-apps pull request #3
Opened 2021-04-07 19:39 UTC by piotrek-janus

changes required for domestic payment consent callback:
- regenerating openbanking swagger client to add  correct content type (application/json)
- HTTP client transport copy-pasted from ACP allowing consent type selection (when more than one available)
- removed some bank API validation for risk (it failed despite risk being empty in both requests (consent and payment)
- redirect to the confetti page

2021-04-07 20:53 UTC, ikawalec requested changes

2021-04-07 20:53 UTC, ikawalec commented on bank/handler.go
> +		}*/
can you create a task to not forget to fix it?

2021-04-07 20:53 UTC, ikawalec commented on financroo/domestic_payment_routes.go
> +								Unstructured: "Unstructured todo", // TODO invoice info?
what's up with this todo?

2021-04-08 07:10 UTC, ikawalec approved these changes
I see that there are some todos in the code, but I would like to merge it to have the basic flow working.

2021-04-08 07:25 UTC, piotrek-janus commented on bank/handler.go
> +		}*/
sure, https://cloudentity.atlassian.net/secure/RapidBoard.jspa?rapidView=180&projectKey=AUT&modal=detail&quickFilter=500&assignee=5fc545fd3b4f590068df36b1

2021-04-08 07:32 UTC, piotrek-janus commented on financroo/domestic_payment_routes.go
> +								Unstructured: "Unstructured todo", // TODO invoice info?
this field was required and wasn't sure what to put there, I will update it in next PR because I still need to add some extra info to the request and response

2021-04-08 07:33 UTC, mbilski approved these changes

2021-04-08 07:33 UTC, mbilski commented on bank/handler.go
> +		logrus.WithField("err", err.Error()).Errorf("failed to introspect token %s", token)
```logrus.WithError(err).Errorf(...)```

2021-04-08 07:33 UTC, mbilski commented on financroo/clients.go
> +	logrus.WithField("producers", tr.Producers).Info("list producers....")
debug?

2021-04-08 07:33 UTC, mbilski commented on financroo/domestic_payment_routes.go
> +			errJson, _ := json.Marshal(err)
hax

2021-04-08 08:04 UTC, piotrek-janus commented on financroo/domestic_payment_routes.go
> +			errJson, _ := json.Marshal(err)
removed

2021-04-08 08:04 UTC, piotrek-janus commented on financroo/clients.go
> +	logrus.WithField("producers", tr.Producers).Info("list producers....")
removed

2021-04-08 08:04 UTC, piotrek-janus commented on bank/handler.go
> +		logrus.WithField("err", err.Error()).Errorf("failed to introspect token %s", token)
fixed

2021-04-08 08:51 UTC, merged